version: '3'

services:
  webmin:
    image: croc/webmin
    environment:
      - ROOT_PASSWORD=MySuperSecretPassword1
    volumes:
      - './backup:/backup'
    ports:
      - '10000:10000'
    restart: always
